# Generated by Django 2.2.4 on 2019-08-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_user_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('responsible_user_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('telegram_username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('chat_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ref_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('amo_account_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('facebook_link', models.URLField(blank=True, default=None, null=True)),
                ('payout_method', models.CharField(default='CC', max_length=20)),
                ('cc_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fb_login', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fb_password', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('ERROR', 'Error'), ('LOG', 'Log')], default='ERROR', max_length=5)),
                ('function_name', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmoLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.BooleanField(default=False)),
                ('amo_lead_id', models.CharField(max_length=100, unique=True)),
                ('amo_status_id', models.CharField(blank=True, max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('amo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coda.AmoUser')),
            ],
        ),
    ]
