# Generated by Django 2.2.4 on 2019-08-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('ERROR', 'Error'), ('LOG', 'Log'), ('WARNING', 'Warning')], default='ERROR', max_length=6),
        ),
        migrations.CreateModel(
            name='FBAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=20, unique=True)),
                ('acc_type', models.CharField(choices=[('GO', 'GO')], default='GO', max_length=20)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('amo_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coda.AmoLead')),
            ],
        ),
    ]
